### ISSUE TITLE
A problem/mistake on processdata.py

### ISSUE THREAD

**Issue by johannwyh** [ZHUTAO142857/avsync#2]
**data/processdata.py**
Line 65:

> ffmpeg -y -i %s -af aresample=sync=1 -ac 1 -vn -acodec pcm_s16le -ar 16000 %s > /dev/null 2>&1

I am not quite familiar with FFmpeg. My FFmpeg version is 3.1.3 and this command does not work for me. After I replace **aresample=sync=1** with **aresample=async=1** the extraction of audio is seemingly correct. 

However, I have no idea what this parameter means and I do not know whether I have changed something that this command should be. Could you explain it more, whether it is a mistake or what config is correct under latest FFmpeg version?

Thank you very much.

**Comment by zhitiankai** [comment]
I also encountered this problem, how do you solve it, thank you

**Comment by zhitiankai** [comment]
我也遇到了这个问题，改成了这样cmd1 = "ffmpeg -y -i %s -async 1 -ac 1 -vn -acodec pcm_s16le -ar 16000 %s" % (mp4path, audiopath)，训练过程出了这个错，IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/work4/zhitiankai/anaconda3/envs/avsync/lib/python2.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/work4/zhitiankai/anaconda3/envs/avsync/lib/python2.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/work4/zhitiankai/avsync/data/processdata.py", line 246, in __getitem__
    vfeat = frames[idx2*5:(idx2+1)*5, :, :]
IndexError: too many indices for array
请问您是如何解决的，谢谢
